# Generated by Django 5.0.4 on 2024-04-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
